# January
Question.create(date: Date.parse("2000-01-01"), body: "What is your number one goal this year?")
Question.create(date: Date.parse("2000-01-02"), body: "What are you most grateful for?")
Question.create(date: Date.parse("2000-01-03"), body: "Are you content?")
Question.create(date: Date.parse("2000-01-04"), body: "What is your best memory of last year?")
Question.create(date: Date.parse("2000-01-05"), body: "What was the last major accomplishment you had?")
Question.create(date: Date.parse("2000-01-06"), body: "What possession could you not live without?")
Question.create(date: Date.parse("2000-01-07"), body: "Can people change?")
Question.create(date: Date.parse("2000-01-08"), body: "What is the last “good” thing you ate?")
Question.create(date: Date.parse("2000-01-09"), body: "What is your current favorite snack?")
Question.create(date: Date.parse("2000-01-10"), body: "What made you smile today?")
Question.create(date: Date.parse("2000-01-11"), body: "What’s your favorite accessory?")
Question.create(date: Date.parse("2000-01-12"), body: "What is making you mad?")
Question.create(date: Date.parse("2000-01-13"), body: "What did you have for dinner today?")
Question.create(date: Date.parse("2000-01-14"), body: "What did you get done?")
Question.create(date: Date.parse("2000-01-15"), body: "Who last called you on the phone?")
Question.create(date: Date.parse("2000-01-16"), body: "Who are you in love with?")
Question.create(date: Date.parse("2000-01-17"), body: "What are you grateful for?")
Question.create(date: Date.parse("2000-01-18"), body: "The best part of today was ______________ .")
Question.create(date: Date.parse("2000-01-19"), body: "My current favorite website is _________________.")
Question.create(date: Date.parse("2000-01-20"), body: "What was the hardest thing you’re dealing with?")
Question.create(date: Date.parse("2000-01-21"), body: "Today I wish I had more _________________.")
Question.create(date: Date.parse("2000-01-22"), body: "Tomorrow will be better because ___________________.")
Question.create(date: Date.parse("2000-01-23"), body: "What made today unusual?")
Question.create(date: Date.parse("2000-01-24"), body: "What are you looking for from life?")
Question.create(date: Date.parse("2000-01-25"), body: "What is your favorite thing to drink?")
Question.create(date: Date.parse("2000-01-26"), body: "Today the temperature was ___________________.")
Question.create(date: Date.parse("2000-01-27"), body: "How much did you spend at the grocery store the last time you went?")
Question.create(date: Date.parse("2000-01-28"), body: "Tomorrow I will _________________________.")
Question.create(date: Date.parse("2000-01-29"), body: "What was your last major purchase?")
Question.create(date: Date.parse("2000-01-30"), body: "My house is a home because _______________________.")
Question.create(date: Date.parse("2000-01-31"), body: "Who is the last person to tell you they loved you?")

# February
Question.create(date: Date.parse("2000-02-01"), body: "What is your favorite piece of art you own?")
Question.create(date: Date.parse("2000-02-02"), body: "The most expensive bill I paid last month was ________.")
Question.create(date: Date.parse("2000-02-03"), body: "What’s the last thing you apologized for?")
Question.create(date: Date.parse("2000-02-04"), body: "My favorite color is ______________.")
Question.create(date: Date.parse("2000-02-05"), body: "On a scale of 1-10 how is your health?")
Question.create(date: Date.parse("2000-02-06"), body: "If you could do today over, would you change anything?")
Question.create(date: Date.parse("2000-02-07"), body: "Name a person you wish you didn’t have to deal with today.")
Question.create(date: Date.parse("2000-02-08"), body: "What is the largest TV screen in your house?")
Question.create(date: Date.parse("2000-02-09"), body: "What time did you go to bed last night?")
Question.create(date: Date.parse("2000-02-10"), body: "What did you buy today?")
Question.create(date: Date.parse("2000-02-11"), body: "I wish I had ____________.")
Question.create(date: Date.parse("2000-02-12"), body: "How many photos did you take today?")
Question.create(date: Date.parse("2000-02-13"), body: "What book are you reading right now?")
Question.create(date: Date.parse("2000-02-14"), body: "How many hours of sleep did you get last night?")
Question.create(date: Date.parse("2000-02-15"), body: "Last thing you wanted but didn’t get.")
Question.create(date: Date.parse("2000-02-16"), body: "What mood were you in today?")
Question.create(date: Date.parse("2000-02-17"), body: "What was the last new thing you tried?")
Question.create(date: Date.parse("2000-02-18"), body: "My biggest hope is _____________.")
Question.create(date: Date.parse("2000-02-19"), body: "What has challenged your morals?")
Question.create(date: Date.parse("2000-02-20"), body: "What kind of car are you driving?")
Question.create(date: Date.parse("2000-02-21"), body: "List your pets.")
Question.create(date: Date.parse("2000-02-22"), body: "What are three things you need to buy?")
Question.create(date: Date.parse("2000-02-23"), body: "Today I felt really secure knowing __________________.")
Question.create(date: Date.parse("2000-02-24"), body: "Whose life did you make a difference in today?")
Question.create(date: Date.parse("2000-02-25"), body: "What is your super power?")
Question.create(date: Date.parse("2000-02-26"), body: "What is annoying you?")
Question.create(date: Date.parse("2000-02-27"), body: "What would have made today perfect?")
Question.create(date: Date.parse("2000-02-28"), body: "What stresses you?")
Question.create(date: Date.parse("2000-02-29"), body: "What did you do to take advantage of this extra day this year?")

# March
Question.create(date: Date.parse("2000-03-01"), body: "The funniest thing you heard today.")
Question.create(date: Date.parse("2000-03-02"), body: "If you could have a new talent what would you want?")
Question.create(date: Date.parse("2000-03-03"), body: "Who is your best friend but not your spouse?")
Question.create(date: Date.parse("2000-03-04"), body: "What do you wish you had left unsaid?")
Question.create(date: Date.parse("2000-03-05"), body: "What was the first thing you ate or drank today?")
Question.create(date: Date.parse("2000-03-06"), body: "Are you saving or spending?")
Question.create(date: Date.parse("2000-03-07"), body: "On a scale of 1-10 how clean is your house? (10 being the cleanest)")
Question.create(date: Date.parse("2000-03-08"), body: "What is the last song you listened to?")
Question.create(date: Date.parse("2000-03-09"), body: "What relaxes you?")
Question.create(date: Date.parse("2000-03-10"), body: "What is the most valuable thing you own?")
Question.create(date: Date.parse("2000-03-11"), body: "What did you find inspiring today?")
Question.create(date: Date.parse("2000-03-12"), body: "Are you happy?")
Question.create(date: Date.parse("2000-03-13"), body: "How much “me” time did you take today?")
Question.create(date: Date.parse("2000-03-14"), body: "List three things you have faith in.")
Question.create(date: Date.parse("2000-03-15"), body: "Who is the last person you said “I love you” to?")
Question.create(date: Date.parse("2000-03-16"), body: "Did you seize any opportunities?")
Question.create(date: Date.parse("2000-03-17"), body: "Where did you go today?")
Question.create(date: Date.parse("2000-03-18"), body: "What advice were you given?")
Question.create(date: Date.parse("2000-03-19"), body: "Today was ________________________.")
Question.create(date: Date.parse("2000-03-20"), body: "What are you glad you did today?")
Question.create(date: Date.parse("2000-03-21"), body: "When was your last vacation? Where did you go?")
Question.create(date: Date.parse("2000-03-22"), body: "The greatest wisdom comes from _____________________.")
Question.create(date: Date.parse("2000-03-23"), body: "Who is your hero?")
Question.create(date: Date.parse("2000-03-24"), body: "Why?")
Question.create(date: Date.parse("2000-03-25"), body: "If you could have read one person’s mind today, who would you choose?")
Question.create(date: Date.parse("2000-03-26"), body: "What was the easiest thing about today?")
Question.create(date: Date.parse("2000-03-27"), body: "Did you thank anyone today?")
Question.create(date: Date.parse("2000-03-28"), body: "Did you work hard today?")
Question.create(date: Date.parse("2000-03-29"), body: "What was in your post office box today?")
Question.create(date: Date.parse("2000-03-30"), body: "Today was a complete ______________________.")
Question.create(date: Date.parse("2000-03-31"), body: "What are you seeking?")

# April
Question.create(date: Date.parse("2000-04-01"), body: "Did you make someone laugh today? Was it intentional?")
Question.create(date: Date.parse("2000-04-02"), body: "What makes you sad?")
Question.create(date: Date.parse("2000-04-03"), body: "Was today typical? Why/Why not?")
Question.create(date: Date.parse("2000-04-04"), body: "Who do you trust the most?")
Question.create(date: Date.parse("2000-04-05"), body: "What’s your next major deadline? What is it for?")
Question.create(date: Date.parse("2000-04-06"), body: "What did you have for breakfast today?")
Question.create(date: Date.parse("2000-04-07"), body: "Do you have any regrets today?")
Question.create(date: Date.parse("2000-04-08"), body: "How did you add art to your life today?")
Question.create(date: Date.parse("2000-04-09"), body: "______________ makes me happy.")
Question.create(date: Date.parse("2000-04-10"), body: "When is the last time you danced?")
Question.create(date: Date.parse("2000-04-11"), body: "List the people you live with.")
Question.create(date: Date.parse("2000-04-12"), body: "What fears did you have today?")
Question.create(date: Date.parse("2000-04-13"), body: "What did you forget?")
Question.create(date: Date.parse("2000-04-14"), body: "What is your favorite TV show?")
Question.create(date: Date.parse("2000-04-15"), body: "I have faith that _________________.")
Question.create(date: Date.parse("2000-04-16"), body: "Who is the last person you kissed?")
Question.create(date: Date.parse("2000-04-17"), body: "What did you wear today?")
Question.create(date: Date.parse("2000-04-18"), body: "What is testing you?")
Question.create(date: Date.parse("2000-04-19"), body: "What’s the oldest thing you’re wearing today?")
Question.create(date: Date.parse("2000-04-20"), body: "List 5 things you should have done today.")
Question.create(date: Date.parse("2000-04-21"), body: "Where did you spend the most time today?")
Question.create(date: Date.parse("2000-04-22"), body: "Share a favorite quote.")
Question.create(date: Date.parse("2000-04-23"), body: "Who did you worry about today?")
Question.create(date: Date.parse("2000-04-24"), body: "Were you creative today? How?")
Question.create(date: Date.parse("2000-04-25"), body: "What is the next major purchase you need to make?")
Question.create(date: Date.parse("2000-04-26"), body: "What is the last thing that made you cry?")
Question.create(date: Date.parse("2000-04-27"), body: "Today was tough because _________________.")
Question.create(date: Date.parse("2000-04-28"), body: "Who are you jealous of?")
Question.create(date: Date.parse("2000-04-29"), body: "Where do you want to go next?")
Question.create(date: Date.parse("2000-04-30"), body: "What did you read today?")

# May
Question.create(date: Date.parse("2000-05-01"), body: "Who was kind to you today?")
Question.create(date: Date.parse("2000-05-02"), body: "Who is the last person you spoke with?")
Question.create(date: Date.parse("2000-05-03"), body: "What makes you feel alive?")
Question.create(date: Date.parse("2000-05-04"), body: "The store I frequent the most is _________________________.")
Question.create(date: Date.parse("2000-05-05"), body: "How did you relax today?")
Question.create(date: Date.parse("2000-05-06"), body: "Describe your favorite pair of shoes you own now.")
Question.create(date: Date.parse("2000-05-07"), body: "What rule had the most impact on your day?")
Question.create(date: Date.parse("2000-05-08"), body: "How many pairs of shoes do you own?")
Question.create(date: Date.parse("2000-05-09"), body: "Today I lost __________________.")
Question.create(date: Date.parse("2000-05-10"), body: "I really wish ___________ hadn’t been invented.")
Question.create(date: Date.parse("2000-05-11"), body: "What’s the most expensive thing you own that you can carry?")
Question.create(date: Date.parse("2000-05-12"), body: "How much money is in your wallet right now?")
Question.create(date: Date.parse("2000-05-13"), body: "Why was today unique?")
Question.create(date: Date.parse("2000-05-14"), body: "What did you leave undone today?")
Question.create(date: Date.parse("2000-05-15"), body: "Today the weather was _________________________.")
Question.create(date: Date.parse("2000-05-16"), body: "What was in your email today?")
Question.create(date: Date.parse("2000-05-17"), body: "What do you wish you had said today?")
Question.create(date: Date.parse("2000-05-18"), body: "What was the biggest decision you made today?")
Question.create(date: Date.parse("2000-05-19"), body: "What are you waiting for?")
Question.create(date: Date.parse("2000-05-20"), body: "What is the prevailing truth about your day.")
Question.create(date: Date.parse("2000-05-21"), body: "What is the last thing you settled for?")
Question.create(date: Date.parse("2000-05-22"), body: "Describe your day in a six word sentence.")
Question.create(date: Date.parse("2000-05-23"), body: "What was the last thing that hurt you?")
Question.create(date: Date.parse("2000-05-24"), body: "Did you use your time wisely today?")
Question.create(date: Date.parse("2000-05-25"), body: "Did you have a dream last night? Describe it.")
Question.create(date: Date.parse("2000-05-26"), body: "Where do you wish you were?")
Question.create(date: Date.parse("2000-05-27"), body: "What music did you hear today?")
Question.create(date: Date.parse("2000-05-28"), body: "What did you have the most fun doing today?")
Question.create(date: Date.parse("2000-05-29"), body: "What do you love most about what you get to do every day?")
Question.create(date: Date.parse("2000-05-30"), body: "What hobbies do you have?")
Question.create(date: Date.parse("2000-05-31"), body: "What was the lowest point of your day?")

# June
Question.create(date: Date.parse("2000-06-01"), body: "List the credit cards in your wallet.")
Question.create(date: Date.parse("2000-06-02"), body: "How close to perfect was today?")
Question.create(date: Date.parse("2000-06-03"), body: "When did you last sing out loud?")
Question.create(date: Date.parse("2000-06-04"), body: "What was the last gathering you attended?")
Question.create(date: Date.parse("2000-06-05"), body: "Did anything make you sad today?")
Question.create(date: Date.parse("2000-06-06"), body: "Share a secret thought.")
Question.create(date: Date.parse("2000-06-07"), body: "List 5 things you wish you invented.")
Question.create(date: Date.parse("2000-06-08"), body: "What’s the last recipe you prepared?")
Question.create(date: Date.parse("2000-06-09"), body: "Who is your most reliable friend?")
Question.create(date: Date.parse("2000-06-10"), body: "What made you lose track of time today?")
Question.create(date: Date.parse("2000-06-11"), body: "What are you confident about?")
Question.create(date: Date.parse("2000-06-12"), body: "How did you do it?")
Question.create(date: Date.parse("2000-06-13"), body: "What is the last purchase you made?")
Question.create(date: Date.parse("2000-06-14"), body: "Did you show someone appreciation today?")
Question.create(date: Date.parse("2000-06-15"), body: "How many push-ups can you do?")
Question.create(date: Date.parse("2000-06-16"), body: "What are you looking forward to?")
Question.create(date: Date.parse("2000-06-17"), body: "What is your favorite dish to prepare?")
Question.create(date: Date.parse("2000-06-18"), body: "There is no such thing as too much _____________________________.")
Question.create(date: Date.parse("2000-06-19"), body: "What is the most important thing you were told today?")
Question.create(date: Date.parse("2000-06-20"), body: "What was the last thing you thought about today?")
Question.create(date: Date.parse("2000-06-21"), body: "What is the last book you read?")
Question.create(date: Date.parse("2000-06-22"), body: "What matters today?")
Question.create(date: Date.parse("2000-06-23"), body: "What project are you working on?")
Question.create(date: Date.parse("2000-06-24"), body: "Without looking at the previous years’ entry first, sign your name.")
Question.create(date: Date.parse("2000-06-25"), body: "What is your most prized possession?")
Question.create(date: Date.parse("2000-06-26"), body: "Were you ‘good’ or ‘bad’ today?")
Question.create(date: Date.parse("2000-06-27"), body: "What is the smartest thing you did today?")
Question.create(date: Date.parse("2000-06-28"), body: "What was in your mailbox today?")
Question.create(date: Date.parse("2000-06-29"), body: "Today I was so ________________.")
Question.create(date: Date.parse("2000-06-30"), body: "The last thing I bought myself was __________________.")

# July
Question.create(date: Date.parse("2000-07-01"), body: "Were you alone today?")
Question.create(date: Date.parse("2000-07-02"), body: "Who was the last person you saw today?")
Question.create(date: Date.parse("2000-07-03"), body: "What do you need to let go of?")
Question.create(date: Date.parse("2000-07-04"), body: "What movie are you looking forward to?")
Question.create(date: Date.parse("2000-07-05"), body: "I just can’t ____________________.")
Question.create(date: Date.parse("2000-07-06"), body: "Who did you text today?")
Question.create(date: Date.parse("2000-07-07"), body: "Have you played the lottery?")
Question.create(date: Date.parse("2000-07-08"), body: "A funny thing happened on the way to _____________________.")
Question.create(date: Date.parse("2000-07-09"), body: "Name one thing you should toss right now, but just can’t.")
Question.create(date: Date.parse("2000-07-10"), body: "What recently happened that made you proud of yourself?")
Question.create(date: Date.parse("2000-07-11"), body: "Who did you see the most today?")
Question.create(date: Date.parse("2000-07-12"), body: "Who inspires you?")
Question.create(date: Date.parse("2000-07-13"), body: "How much is gasoline per gallon?")
Question.create(date: Date.parse("2000-07-14"), body: "What was your horoscope today? Was it accurate?")
Question.create(date: Date.parse("2000-07-15"), body: "What are you most afraid of?")
Question.create(date: Date.parse("2000-07-16"), body: "What’s the biggest thing you have going on?")
Question.create(date: Date.parse("2000-07-17"), body: "What did you accomplish today?")
Question.create(date: Date.parse("2000-07-18"), body: "Did you act your age today?")
Question.create(date: Date.parse("2000-07-19"), body: "How busy was your day today?")
Question.create(date: Date.parse("2000-07-20"), body: "What was the hurry?")
Question.create(date: Date.parse("2000-07-21"), body: "What is your address?")
Question.create(date: Date.parse("2000-07-22"), body: "What do you wish there was less of in the world?")
Question.create(date: Date.parse("2000-07-23"), body: "What is stopping you?")
Question.create(date: Date.parse("2000-07-24"), body: "What were your chores today?")
Question.create(date: Date.parse("2000-07-25"), body: "What was the last thing that made you laugh out loud?")
Question.create(date: Date.parse("2000-07-26"), body: "Who did you eat dinner with?")
Question.create(date: Date.parse("2000-07-27"), body: "How did you make a difference in the world today?")
Question.create(date: Date.parse("2000-07-28"), body: "What is one thing you take with you everywhere?")
Question.create(date: Date.parse("2000-07-29"), body: "The last gift I’ve given was ________________.")
Question.create(date: Date.parse("2000-07-30"), body: "What motivated you today?")
Question.create(date: Date.parse("2000-07-31"), body: "Who is your craziest friend?")

# August
Question.create(date: Date.parse("2000-08-01"), body: "What did you have for lunch today?")
Question.create(date: Date.parse("2000-08-02"), body: "What did you let go of?")
Question.create(date: Date.parse("2000-08-03"), body: "What is the one thing you want to accomplish tomorrow?")
Question.create(date: Date.parse("2000-08-04"), body: "What was the last gift you gave?")
Question.create(date: Date.parse("2000-08-05"), body: "The last time I exercised ____________________.")
Question.create(date: Date.parse("2000-08-06"), body: "What did you create today?")
Question.create(date: Date.parse("2000-08-07"), body: "What memories did you think about today?")
Question.create(date: Date.parse("2000-08-08"), body: "What is the last risk you took?")
Question.create(date: Date.parse("2000-08-09"), body: "What made you compromise?")
Question.create(date: Date.parse("2000-08-10"), body: "Who do you look up to?")
Question.create(date: Date.parse("2000-08-11"), body: "On a scale of 1-10 my day was a __________.")
Question.create(date: Date.parse("2000-08-12"), body: "What did the last text message you received say?")
Question.create(date: Date.parse("2000-08-13"), body: "Do you owe anyone money?")
Question.create(date: Date.parse("2000-08-14"), body: "What is your own favorite physical feature?")
Question.create(date: Date.parse("2000-08-15"), body: "What was the worst thing you ate today?")
Question.create(date: Date.parse("2000-08-16"), body: "I hope no one was looking when I _______________.")
Question.create(date: Date.parse("2000-08-17"), body: "How many miles did you drive/ride today?")
Question.create(date: Date.parse("2000-08-18"), body: "Who was the first person you saw today?")
Question.create(date: Date.parse("2000-08-19"), body: "What’s your biggest phobia?")
Question.create(date: Date.parse("2000-08-20"), body: "What was your first full thought this morning?")
Question.create(date: Date.parse("2000-08-21"), body: "How full is your fridge?")
Question.create(date: Date.parse("2000-08-22"), body: "What was the last healthy thing you did for yourself?")
Question.create(date: Date.parse("2000-08-23"), body: "What did you have to wait for today?")
Question.create(date: Date.parse("2000-08-24"), body: "What did you win?")
Question.create(date: Date.parse("2000-08-25"), body: "Who had the biggest influence on your day?")
Question.create(date: Date.parse("2000-08-26"), body: "What can you learn from today?")
Question.create(date: Date.parse("2000-08-27"), body: "What was the highest point of your day today?")
Question.create(date: Date.parse("2000-08-28"), body: "Did you pay it forward?")
Question.create(date: Date.parse("2000-08-29"), body: "What would you like to learn more about?")
Question.create(date: Date.parse("2000-08-30"), body: "What new TV show do you refuse to watch?")
Question.create(date: Date.parse("2000-08-31"), body: "How much is a gallon of milk?")

# September
Question.create(date: Date.parse("2000-09-01"), body: "What decision do you wish you didn’t have to make?")
Question.create(date: Date.parse("2000-09-02"), body: "What are you questioning?")
Question.create(date: Date.parse("2000-09-03"), body: "What was the most recent thing you learned?")
Question.create(date: Date.parse("2000-09-04"), body: "Where would you like to go?")
Question.create(date: Date.parse("2000-09-05"), body: "The last doctor’s appointment you made was because ___________.")
Question.create(date: Date.parse("2000-09-06"), body: "Name 3 things you should have done today.")
Question.create(date: Date.parse("2000-09-07"), body: "What is the last thing you felt guilty about?")
Question.create(date: Date.parse("2000-09-08"), body: "My life would be easier if __________________.")
Question.create(date: Date.parse("2000-09-09"), body: "Does anyone owe you money?")
Question.create(date: Date.parse("2000-09-10"), body: "When is the last time you intentionally ‘wasted’ a day?")
Question.create(date: Date.parse("2000-09-11"), body: "What is your favorite gadget?")
Question.create(date: Date.parse("2000-09-12"), body: "The computer I use the most is _______________________.")
Question.create(date: Date.parse("2000-09-13"), body: "How did you spend your free time today?")
Question.create(date: Date.parse("2000-09-14"), body: "Were you stressed today? Why?")
Question.create(date: Date.parse("2000-09-15"), body: "What was the last thing you said to another person?")
Question.create(date: Date.parse("2000-09-16"), body: "Who threw the last party you went to?")
Question.create(date: Date.parse("2000-09-17"), body: "What went perfectly about your day?")
Question.create(date: Date.parse("2000-09-18"), body: "How old do you feel?")
Question.create(date: Date.parse("2000-09-19"), body: "OMG! __________________.")
Question.create(date: Date.parse("2000-09-20"), body: "What pressure did you feel today?")
Question.create(date: Date.parse("2000-09-21"), body: "The last gift I’ve received was ________________.")
Question.create(date: Date.parse("2000-09-22"), body: "If you could change today would you?")
Question.create(date: Date.parse("2000-09-23"), body: "I believe ___________________.")
Question.create(date: Date.parse("2000-09-24"), body: "What do you wish you could have skipped today?")
Question.create(date: Date.parse("2000-09-25"), body: "Were you in control of your day?")
Question.create(date: Date.parse("2000-09-26"), body: "What made today worthwhile?")
Question.create(date: Date.parse("2000-09-27"), body: "Were you a good listener today?")
Question.create(date: Date.parse("2000-09-28"), body: "I never ______________________.")
Question.create(date: Date.parse("2000-09-29"), body: "Have you broken the law? How so?")
Question.create(date: Date.parse("2000-09-30"), body: "Were you bored today?")

# October
Question.create(date: Date.parse("2000-10-01"), body: "Who is the last person you spent quality time with?")
Question.create(date: Date.parse("2000-10-02"), body: "Who did you hug today?")
Question.create(date: Date.parse("2000-10-03"), body: "Describe your day in one word.")
Question.create(date: Date.parse("2000-10-04"), body: "How are you?")
Question.create(date: Date.parse("2000-10-05"), body: "Did you do more talking or listening today?")
Question.create(date: Date.parse("2000-10-06"), body: "How much is a gallon of gas?")
Question.create(date: Date.parse("2000-10-07"), body: "What was the last stupid thing you did?")
Question.create(date: Date.parse("2000-10-08"), body: "What’s the next book you are going to read?")
Question.create(date: Date.parse("2000-10-09"), body: "What was the mistake?")
Question.create(date: Date.parse("2000-10-10"), body: "What was the last gift you gave?")
Question.create(date: Date.parse("2000-10-11"), body: "What is your mission?")
Question.create(date: Date.parse("2000-10-12"), body: "If others described how you acted today in one word, it would be _________.")
Question.create(date: Date.parse("2000-10-13"), body: "What is your current bank balance?")
Question.create(date: Date.parse("2000-10-14"), body: "Describe the last piece of furniture you purchased.")
Question.create(date: Date.parse("2000-10-15"), body: "What time did you wake up this morning?")
Question.create(date: Date.parse("2000-10-16"), body: "Describe the last time you were embarrassed.")
Question.create(date: Date.parse("2000-10-17"), body: "How did you improve yourself today?")
Question.create(date: Date.parse("2000-10-18"), body: "How much time did you spend outside today?")
Question.create(date: Date.parse("2000-10-19"), body: "In one year from today, what word do you hope best describes your life.")
Question.create(date: Date.parse("2000-10-20"), body: "Who in your life is crazy talented? What is their talent?")
Question.create(date: Date.parse("2000-10-21"), body: "What do you wish there was more of in the world?")
Question.create(date: Date.parse("2000-10-22"), body: "My favorite sound is _________________ .")
Question.create(date: Date.parse("2000-10-23"), body: "What impact do you hope to have on the world?")
Question.create(date: Date.parse("2000-10-24"), body: "If you made laws, what one would you make today?")
Question.create(date: Date.parse("2000-10-25"), body: "Describe your last life-changing moment.")
Question.create(date: Date.parse("2000-10-26"), body: "What opportunity are you waiting for?")
Question.create(date: Date.parse("2000-10-27"), body: "How many emails did you have today?")
Question.create(date: Date.parse("2000-10-28"), body: "What is the last movie you saw?")
Question.create(date: Date.parse("2000-10-29"), body: "Are you settling for something?")
Question.create(date: Date.parse("2000-10-30"), body: "What is standing in your way?")
Question.create(date: Date.parse("2000-10-31"), body: "What was the happiest headline in the news today? ")

# November
Question.create(date: Date.parse("2000-11-01"), body: "What decision are you glad you made?")
Question.create(date: Date.parse("2000-11-02"), body: "Share some good advice.")
Question.create(date: Date.parse("2000-11-03"), body: "What occupied your mind today?")
Question.create(date: Date.parse("2000-11-04"), body: "What was the best conversation you had today?")
Question.create(date: Date.parse("2000-11-05"), body: "Do you love your job?")
Question.create(date: Date.parse("2000-11-06"), body: "If you could get rid of one of your habits, what would it be?")
Question.create(date: Date.parse("2000-11-07"), body: "List 5 things you wish you had with you today.")
Question.create(date: Date.parse("2000-11-08"), body: "What are the achievements you are most proud of?")
Question.create(date: Date.parse("2000-11-09"), body: "What gadgets did you use today?")
Question.create(date: Date.parse("2000-11-10"), body: "What shocked you?")
Question.create(date: Date.parse("2000-11-11"), body: "What was the last lie you told?")
Question.create(date: Date.parse("2000-11-12"), body: "What is your favorite cuisine?")
Question.create(date: Date.parse("2000-11-13"), body: "What do you have too much of?")
Question.create(date: Date.parse("2000-11-14"), body: "What do you want to tell yourself in one year?")
Question.create(date: Date.parse("2000-11-15"), body: "What is your greatest strength?")
Question.create(date: Date.parse("2000-11-16"), body: "Other than your clothes, what was with you the majority of the day?")
Question.create(date: Date.parse("2000-11-17"), body: "What’s your guilty pleasure?")
Question.create(date: Date.parse("2000-11-18"), body: "What is bothering you?")
Question.create(date: Date.parse("2000-11-19"), body: "What inspires you?")
Question.create(date: Date.parse("2000-11-20"), body: "What impression did you make on others today?")
Question.create(date: Date.parse("2000-11-21"), body: "What did you give up on today?")
Question.create(date: Date.parse("2000-11-22"), body: "How did you play today?")
Question.create(date: Date.parse("2000-11-23"), body: "How do you know?")
Question.create(date: Date.parse("2000-11-24"), body: "Name the last three things you used today.")
Question.create(date: Date.parse("2000-11-25"), body: "What sound do you hate hearing?")
Question.create(date: Date.parse("2000-11-26"), body: "Do you feel appreciated?")
Question.create(date: Date.parse("2000-11-27"), body: "My body is ______________________.")
Question.create(date: Date.parse("2000-11-28"), body: "Today I had too much ________________.")
Question.create(date: Date.parse("2000-11-29"), body: "What worries you?")
Question.create(date: Date.parse("2000-11-30"), body: "What did you get to do today?")

# December
Question.create(date: Date.parse("2000-12-01"), body: "Who is your best friend?")
Question.create(date: Date.parse("2000-12-02"), body: "I really wish _________________.")
Question.create(date: Date.parse("2000-12-03"), body: "Who is the first person you saw today?")
Question.create(date: Date.parse("2000-12-04"), body: "What memory do you want to keep from today?")
Question.create(date: Date.parse("2000-12-05"), body: "How much money is in your wallet?")
Question.create(date: Date.parse("2000-12-06"), body: "What makes you sweat?")
Question.create(date: Date.parse("2000-12-07"), body: "What do you wish your job was?")
Question.create(date: Date.parse("2000-12-08"), body: "What relationship did you nurture today?")
Question.create(date: Date.parse("2000-12-09"), body: "What are you passionate about?")
Question.create(date: Date.parse("2000-12-10"), body: "I realize tomorrow __________________.")
Question.create(date: Date.parse("2000-12-11"), body: "Are you holding a grudge?")
Question.create(date: Date.parse("2000-12-12"), body: "What was weird about your day?")
Question.create(date: Date.parse("2000-12-13"), body: "How much of your day did you spend completely alone?")
Question.create(date: Date.parse("2000-12-14"), body: "How are you expanding your mind?")
Question.create(date: Date.parse("2000-12-15"), body: "What word are you using too much lately?")
Question.create(date: Date.parse("2000-12-16"), body: "How was your day today?")
Question.create(date: Date.parse("2000-12-17"), body: "What was the first thing you saw when you woke up this morning?")
Question.create(date: Date.parse("2000-12-18"), body: "What are three things you need to do tomorrow?")
Question.create(date: Date.parse("2000-12-19"), body: "What is the last place you visited online?")
Question.create(date: Date.parse("2000-12-20"), body: "Today I chose to ________________.")
Question.create(date: Date.parse("2000-12-21"), body: "Were you a positive or negative person today?")
Question.create(date: Date.parse("2000-12-22"), body: "Who is the strongest person you know?")
Question.create(date: Date.parse("2000-12-23"), body: "Who do you wish had been a part of your day?")
Question.create(date: Date.parse("2000-12-24"), body: "What is one thing you were told today that you don’t want to forget?")
Question.create(date: Date.parse("2000-12-25"), body: "What was your weakness today?")
Question.create(date: Date.parse("2000-12-26"), body: "The music genre I listen to the most is ________________.")
Question.create(date: Date.parse("2000-12-27"), body: "How much did you eat today?")
Question.create(date: Date.parse("2000-12-28"), body: "What’s worth fighting for?")
Question.create(date: Date.parse("2000-12-29"), body: "Today I felt ___________________.")
Question.create(date: Date.parse("2000-12-30"), body: "Did you smile or frown more today?")
Question.create(date: Date.parse("2000-12-31"), body: "What improvements are you making?")
